name: setting up environment

on: [push]
    
env:
 username: MDSHAHED7
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           sudo apt install expect -y
           
       - name: cloning repo
         continue-on-error: true
         run: |
           git clone https://github.com/MDSHAHED7/PublicLeech source
           git config --global user.name "ElytrA8"
           git config --global user.email "manofuranium@gmail.com"
       - name: compilation
         continue-on-error: true
         run: |
           ls
           cd source
           docker container prune --force
           docker build . -t leecher
       - name: running Docker
         timeout-minutes: 340
         continue-on-error: true
         run: |
           docker run leecher
           
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/$username/leecher-workflow loop
              cd loop
              echo "1" >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop"
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"${{ secrets.GHUSER }}\r\"
              expect \"Password\"
              send \"${{ secrets.GHPASS }}\r\"
              expect \"main -> main\"
              set timeout -10
              interact"
              
